// English text for the portfolio. Each line is one piece of text on the page.
// Edit the text on the right of each colon — that's all you need to touch.
window.I18N = window.I18N || {};
window.I18N.en = {
  "system_boot": "// SYSTEM BOOT",
  "loading_wedad_salem_profile": "LOADING WEDAD_SALEM.profile",
  "skills": "Skills",
  "experience": "Experience",
  "projects": "Projects",
  "education": "Education",
  "contact": "Contact",
  "online_open_to_work": "ONLINE · OPEN TO WORK",
  "game_programmer_saudi_arabia": "// GAME PROGRAMMER — SAUDI ARABIA",
  "wedad_salem": "WEDAD SALEM",
  "building_gameplay_systems_me": "Building gameplay systems, mechanics, and UI in Unity and C# since 2021, across studio and freelance work. Shipped a mobile game to Google Play with FitNot, programmed educational mini-games at GamifierSA, and mentored Unity students at DigiPen during Gamers8. I'm comfortable handling features from prototype to release, including debugging on real player devices.",
  "view_projects": "▶ View Projects",
  "get_in_touch": "✉ Get in Touch",
  "lvl_4": "LVL 4",
  "class": "CLASS",
  "game_programmer": "Game Programmer",
  "specialization": "SPECIALIZATION",
  "active_since": "ACTIVE SINCE",
  "platforms": "PLATFORMS",
  "mobile_pc_web": "Mobile · PC · Web",
  "guild": "GUILD",
  "freelance": "Freelance",
  "xp_years_active": "XP — YEARS ACTIVE",
  "01_skills": "// 01 — SKILLS",
  "languages": "Languages",
  "engines_and_tools": "Engines &amp; Tools",
  "gameplay_programming": "Gameplay Programming",
  "mechanics": "Mechanics",
  "ui_systems": "UI Systems",
  "animation": "Animation",
  "mobile_optimization": "Mobile Optimization",
  "architecture_and_patterns": "Architecture &amp; Patterns",
  "observer_pattern": "Observer Pattern",
  "backend_and_services": "Backend &amp; Services",
  "version_control": "Version Control",
  "platforms_2": "Platforms",
  "mobile_android": "Mobile — Android",
  "mobile_ios": "Mobile — iOS",
  "web": "Web",
  "pc": "PC",
  "02_experience": "// 02 — EXPERIENCE",
  "2025_present_remote": "2025 — PRESENT · REMOTE",
  "freelance_game_developer": "Freelance Game Developer",
  "independent": "Independent",
  "delivered_unity_game_develop": "Delivered Unity game development and software projects for clients on short-term contracts, working on features end-to-end from scope to delivery.",
  "dec_2023_may_2024_remote": "DEC 2023 — MAY 2024 · REMOTE",
  "shipped_3_mobile_games_as_th": "Shipped 3 mobile games as the sole or lead programmer on small teams, owning Unity / C# gameplay code from spec to release.",
  "collaborated_closely_with_de": "Collaborated closely with designers and artists across iteration cycles to refine mechanics and ship on schedule.",
  "jul_2023_sep_2023_riyadh_ksa": "JUL 2023 — SEP 2023 · RIYADH, KSA",
  "game_development_instructor": "Game Development Instructor",
  "mentored_student_teams_durin": "Mentored student teams during the Gamers8 program, guiding them from concept to a playable Unity build across a multi-week sprint.",
  "oct_2022_apr_2023_riyadh_ksa": "OCT 2022 — APR 2023 · RIYADH, KSA",
  "game_developer_incubator": "Game Developer (Incubator)",
  "selected_for_an_internationa": "Selected for an international games-focused Incubator; developed a game concept under industry mentorship and pitched to investors and publishers.",
  "feb_2022_apr_2022_remote": "FEB 2022 — APR 2022 · REMOTE",
  "shipped_a_unity_mobile_game_": "Shipped a Unity mobile game to the Google Play Store, contributing across gameplay code, UI, and release.",
  "coordinated_remotely_with_th": "Coordinated remotely with the team using Git and GitHub.",
  "03_projects": "// 03 — PROJECTS",
  "unity_pc": "Unity · PC",
  "cybersecurity_educational_ga": "Cybersecurity Educational Game",
  "freelance_2025": "Freelance · 2025",
  "designed_and_built_a_4_stage": "Designed and built a 4-stage educational game from scratch for a client, with a different gameplay mechanic per stage, drag-and-drop, shooter, card-sorting, and quiz.",
  "built_supporting_systems_end": "Built supporting systems end-to-end: player auth, save data, in-game economy and shop, end-of-game certificate, and a performance report.",
  "unity_ecs_dots": "Unity · ECS / DOTS",
  "battle_simulator": "Battle Simulator",
  "personal_2024": "Personal · 2024",
  "unity_ecs_strategy_game_wher": "Unity ECS strategy game where players compose a Blue Team to counter a procedurally generated Red Team each match.",
  "built_on_a_data_oriented_arc": "Built on a data-oriented architecture for modularity and performance at high entity counts, unit behaviors and stats can be swapped without touching combat code.",
  "unity_mobile_web": "Unity · Mobile Web",
  "sole_programmer_on_a_mobile_": "Sole programmer on a mobile web game launched for Eid al-Fitr, featuring a collection of quick, random mini-games inspired by Eid traditions.",
  "owned_the_full_unity_codebas": "Owned the full Unity codebase from gameplay logic to release.",
  "unity_mobile": "Unity · Mobile",
  "jaber_chem_electron_configur": "Jaber Chem — Electron Configuration",
  "programmed_the_complete_elec": "Programmed the complete Electron Configuration mini-game for Jaber Chem, an educational chemistry title.",
  "built_a_shooter_style_mechan": "Built a shooter-style mechanic where players fire electrons to fill atomic configurations.",
  "04_education": "// 04 — EDUCATION",
  "oct_2022_jun_2023_riyadh_ksa": "OCT 2022 — JUN 2023 · RIYADH, KSA",
  "ios_app_developer_program": "iOS App Developer Program",
  "9_month_challenge_based_lear": "9-month Challenge-Based Learning program. Shipped four iOS apps in Swift / Xcode with cross-functional teams.",
  "jul_2021_nov_2021_remote": "JUL 2021 — NOV 2021 · REMOTE",
  "game_development_bootcamp": "Game Development Bootcamp",
  "intensive_program_covering_u": "Intensive program covering Unity, C#, game design, UX, multiplayer patterns, and mobile publishing.",
  "jan_2016_apr_2021": "JAN 2016 — APR 2021",
  "b_sc_computer_science": "B.Sc. Computer Science",
  "taibah_university": "Taibah University",
  "arabic_native": "Arabic — Native",
  "english_advanced": "English — Advanced",
  "05_contact": "// 05 — CONTACT",
  "email": "Email",
  "phone": "Phone",
  "location": "Location",
  "saudi_arabia": "Saudi Arabia",
  "profiles": "Profiles",
  "2026_wedad_salem": "© 2026 WEDAD SALEM",
  "build_v2026_1": "BUILD v2026.1"
};
