// النص العربي للموقع. كل سطر هو نص واحد في الصفحة.
// Edit the text on the right of each colon — that's all you need to touch.
window.I18N = window.I18N || {};
window.I18N.ar = {
  "system_boot": "// تشغيل جهاز الأركيد",
  "loading_wedad_salem_profile": "تحميل WEDAD_SALEM.CAB",
  "skills": "المهارات",
  "experience": "الخبرة",
  "projects": "المشاريع",
  "education": "التعليم",
  "contact": "تواصل",
  "online_open_to_work": "متصلة · متاحة للعمل",
  "game_programmer_saudi_arabia": "// مبرمجة ألعاب — المملكة العربية السعودية",
  "wedad_salem": "وداد سالم",
  "building_gameplay_systems_me": "أبني أنظمة الألعاب والميكانيكات وواجهات المستخدم بـ Unity و C# منذ عام 2021، في العمل ضمن الفرق والمستقل. أطلقت لعبة موبايل على Google Play مع FitNot، وبرمجت ألعاباً تعليمية مصغّرة في GamifierSA، ودرّبت طلاب Unity في DigiPen خلال برنامج Gamers8. أصمم الألعاب من البداية للنهاية: تجربة الميكانيكا، إطلاقها، ثم تصحيح أخطائها على أي جهاز يحمله لاعب حقيقي.",
  "view_projects": "▶ عرض المشاريع",
  "get_in_touch": "✉ تواصل معي",
  "lvl_4": "المستوى 4",
  "class": "الفئة",
  "game_programmer": "مبرمجة ألعاب",
  "specialization": "التخصص",
  "active_since": "نشطة منذ",
  "platforms": "المنصات",
  "mobile_pc_web": "موبايل · حاسوب · ويب",
  "guild": "النقابة",
  "freelance": "مستقلة",
  "xp_years_active": "نقاط الخبرة — سنوات النشاط",
  "01_skills": "// 01 — المهارات",
  "languages": "اللغات",
  "engines_and_tools": "المحركات والأدوات",
  "gameplay_programming": "برمجة تجربة اللعب",
  "mechanics": "الميكانيكات",
  "ui_systems": "أنظمة الواجهة",
  "animation": "الرسوم المتحركة",
  "mobile_optimization": "تحسين أداء الموبايل",
  "architecture_and_patterns": "البنية والأنماط البرمجية",
  "observer_pattern": "نمط المراقب (Observer)",
  "backend_and_services": "الخدمات الخلفية",
  "version_control": "التحكم بالإصدارات",
  "platforms_2": "المنصات",
  "mobile_android": "موبايل — أندرويد",
  "mobile_ios": "موبايل — iOS",
  "web": "ويب",
  "pc": "حاسوب",
  "02_experience": "// 02 — الخبرة",
  "rank_label": "الترتيب",
  "role_label": "الدور",
  "date_label": "التاريخ",
  "rank_1": "الأول",
  "rank_2": "الثاني",
  "rank_3": "الثالث",
  "rank_4": "الرابع",
  "rank_5": "الخامس",
  "2025_present_remote": "2025 — حتى الآن · عن بُعد",
  "freelance_game_developer": "مطوّرة ألعاب مستقلة",
  "independent": "مستقلة",
  "delivered_unity_game_develop": "نفّذت مشاريع تطوير ألعاب وبرمجيات بـ Unity لعملاء بعقود قصيرة المدى، مع العمل على الميزات من البداية حتى التسليم.",
  "dec_2023_may_2024_remote": "ديسمبر 2023 — مايو 2024 · عن بُعد",
  "shipped_3_mobile_games_as_th": "أطلقت 3 ألعاب موبايل كمبرمجة منفردة أو رئيسية في فرق صغيرة، مع امتلاك كود اللعب بـ Unity / C# من المواصفات حتى الإطلاق.",
  "collaborated_closely_with_de": "تعاونت بشكل وثيق مع المصممين والفنانين عبر دورات التكرار لتحسين الميكانيكات والإطلاق في الوقت المحدد.",
  "jul_2023_sep_2023_riyadh_ksa": "يوليو 2023 — سبتمبر 2023 · الرياض، السعودية",
  "game_development_instructor": "مدرّبة تطوير ألعاب",
  "mentored_student_teams_durin": "أرشدت فرق طلاب خلال برنامج Gamers8، من الفكرة إلى نسخة قابلة للّعب بـ Unity عبر سباق عمل متعدد الأسابيع.",
  "oct_2022_apr_2023_riyadh_ksa": "أكتوبر 2022 — أبريل 2023 · الرياض، السعودية",
  "game_developer_incubator": "مطوّرة ألعاب (حاضنة)",
  "selected_for_an_internationa": "تم اختياري لبرنامج حاضنات عالمي متخصص في الألعاب؛ طوّرت فكرة لعبة بتوجيه من خبراء الصناعة وقدّمتها لمستثمرين وناشرين.",
  "feb_2022_apr_2022_remote": "فبراير 2022 — أبريل 2022 · عن بُعد",
  "shipped_a_unity_mobile_game_": "أطلقت لعبة موبايل بـ Unity على متجر Google Play، بالمساهمة في كود اللعب والواجهة والإطلاق.",
  "coordinated_remotely_with_th": "التنسيق مع الفريق عن بُعد باستخدام Git و GitHub.",
  "03_projects": "// 03 — المشاريع",
  "unity_pc": "يونيتي · حاسوب",
  "cybersecurity_educational_ga": "لعبة تعليمية للأمن السيبراني",
  "freelance_2025": "عمل مستقل · 2025",
  "designed_and_built_a_4_stage": "صمّمت وبنيت لعبة تعليمية من 4 مراحل من الصفر لعميل، بميكانيكا لعب مختلفة في كل مرحلة، السحب والإفلات، الرماية، ترتيب البطاقات، والاختبار.",
  "built_supporting_systems_end": "بنيت الأنظمة الداعمة بالكامل: تسجيل دخول اللاعب، حفظ البيانات، اقتصاد ومتجر داخل اللعبة، شهادة نهاية اللعبة، وتقرير أداء.",
  "unity_ecs_dots": "يونيتي · ECS / DOTS",
  "battle_simulator": "محاكي المعارك",
  "personal_2024": "مشروع شخصي · 2024",
  "unity_ecs_strategy_game_wher": "لعبة استراتيجية بـ Unity ECS يكوّن فيها اللاعبون فريقاً أزرق لمواجهة فريق أحمر يُولَّد عشوائياً في كل مباراة.",
  "built_on_a_data_oriented_arc": "مبنية على data-oriented architecture لمرونة وأداء عاليين مع أعداد كبيرة من الكيانات، يمكن تبديل سلوكيات وإحصاءات الوحدات دون لمس كود القتال.",
  "unity_mobile_web": "يونيتي · ويب موبايل",
  "sole_programmer_on_a_mobile_": "المبرمجة الوحيدة في لعبة ويب للموبايل أُطلقت بمناسبة عيد الفطر، تضم مجموعة من الألعاب المصغّرة السريعة والعشوائية المستوحاة من تقاليد العيد.",
  "owned_the_full_unity_codebas": "امتلكت كود Unity بالكامل من منطق اللعب حتى الإطلاق.",
  "unity_mobile": "يونيتي · موبايل",
  "jaber_chem_electron_configur": "صنعة جابر — التوزيع الإلكتروني",
  "programmed_the_complete_elec": "برمجت لعبة التوزيع الإلكتروني المصغّرة بالكامل لـ Jaber Chem، وهي لعبة تعليمية في الكيمياء.",
  "built_a_shooter_style_mechan": "بنيت ميكانيكا على طراز الرماية يطلق فيها اللاعبون إلكترونات لملء التوزيعات الذرية.",
  "04_education": "// 04 — التعليم",
  "oct_2022_jun_2023_riyadh_ksa": "أكتوبر 2022 — يونيو 2023 · الرياض، السعودية",
  "ios_app_developer_program": "برنامج تطوير تطبيقات iOS",
  "9_month_challenge_based_lear": "برنامج تعلّم قائم على التحديات لمدة 9 أشهر. أطلقت أربع تطبيقات iOS بـ Swift / Xcode مع فرق متعددة التخصصات.",
  "jul_2021_nov_2021_remote": "يوليو 2021 — نوفمبر 2021 · عن بُعد",
  "game_development_bootcamp": "معسكر تطوير الألعاب",
  "intensive_program_covering_u": "برنامج مكثّف يغطي Unity وC# وتصميم الألعاب وتجربة المستخدم وأنماط اللعب الجماعي والنشر على الموبايل.",
  "jan_2016_apr_2021": "يناير 2016 — أبريل 2021",
  "b_sc_computer_science": "بكالوريوس علوم الحاسب",
  "taibah_university": "جامعة طيبة",
  "arabic_native": "العربية — اللغة الأم",
  "english_advanced": "الإنجليزية — متقدمة",
  "05_contact": "// 05 — تواصل",
  "continue_prompt": "استمرار؟",
  "continue_hint": "— التفاصيل أدناه —",
  "email": "البريد الإلكتروني",
  "phone": "الهاتف",
  "location": "الموقع",
  "saudi_arabia": "المملكة العربية السعودية",
  "profiles": "الملفات",
  "2026_wedad_salem": "© 2026 وداد سالم",
  "build_v2026_1": "الإصدار v2026.1"
};